[package]
name = "air"
version = "0.11.0"
authors = ["Fluence Labs"]
edition = "2018"
publish = false

[lib]
name = "air"
path = "src/lib.rs"
doctest = false

[dependencies]
air-parser = { path = "../crates/air-parser" }
polyplets = { path = "../crates/polyplets" }
air-interpreter-data = { path = "../crates/interpreter-data" }
air-interpreter-interface = { path = "../crates/interpreter-interface" }
fluence = { version = "0.6.8", features = ["logger"] }

serde = { version = "=1.0.118", features = [ "derive", "rc" ] }
serde_json = "=1.0.61"

jsonpath_lib-fl = "=0.3.7"

boolinator = "2.4.0"
log = "0.4.11"
thiserror = "1.0.23"

# Keep 0.2.65 until this is resolved https://github.com/rustwasm/wasm-pack/issues/886
wasm-bindgen = "=0.2.65"

[dev_dependencies]
air-test-utils = { path = "../crates/test-utils" }
fluence-app-service = "0.7.0"

criterion = "0.3.3"
csv = "1.1.5"
once_cell = "1.4.1"
env_logger = "0.7.1"
maplit = "1.0.2"
pretty_assertions = "0.6.1"
serde_json = "1.0.56"

[[bench]]
name = "call_benchmark"
harness = false

[[bench]]
name = "chat_benchmark"
harness = false

[[bench]]
name = "create_service_benchmark"
harness = false

[features]
# indicates that this library should be compiled for the wasm bindgen target
# otherwise it will be compiled to the Marine target
marine = []
