[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/air"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
serde = {version = "=1.0.118", features = ["derive", "rc"]}
serde_json = "1.0.56"
semver = { version = "1.0.3", features = ["serde"] }
once_cell = "1.8.0"
