[package]
name = "avm-server"
description = "Fluence AIR VM"
version = "0.7.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"

[lib]
name = "avm_server"
path = "src/lib.rs"

[dependencies]
fluence-faas = { git = "https://github.com/fluencelabs/marine", branch = "memory_leak_test_3" }
air-interpreter-interface = { version = "0.5.0", path = "../../crates/interpreter-interface" }

thiserror = "1.0.24"
maplit = "1.0.2"
serde_json = "1.0.60"
serde = "=1.0.118"
log = "0.4.14"
parking_lot = "0.11.1"

[features]
# enable raw AVM API intended for testing
raw-avm-api = []
